from genetic_algorithm.methods.selection.cutoff_selection import CutoffSelection
from genetic_algorithm.methods.selection.graceful_cutoff_selection import GracefulCutoffSelection
from genetic_algorithm.methods.selection.random_walk_selection import RandomWalkSelection
from genetic_algorithm.methods.selection.roulette_selection import RouletteSelection