# ===== General ===== #
seed: 69
only_model: False
dataset: DIGITS
normalized: True
dataset_args: {"classes": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]} # Will be overwritten
name: top_speed_normalized
log: True
log_every: 50 # 10, 50
device: cpu

# ===== Genetic algorithm methods ===== #
generation_method: negligent_generation
recombination_method: random_point_crossover_negligent_recombination
mutation_method: single_point_negligent_optimized_mutation
survivor_evaluation_method: population_ranking_evaluation
parents_evaluation_method: population_performance_evaluation
individual_evaluation_method: individual_performance_evaluation
evaluation_cache_type: fitness_hash_table
survivor_selection_method: cutoff_selection

# ===== Method parameterization  ===== #
generation_args: {"model": True, "prune_rate_init": 0.5}
recombination_args: {}
mutation_args: {}
survivor_evaluation_args: {"performance_maximizing": False, "sparsity_maximizing": True}
parents_evaluation_args: {"performance_maximizing": False}
individual_evaluation_args: {"quality_metric": "CE", "model": True, "train_loader": True, "device": True}
evaluation_cache_args: {}
survivor_selection_args: {}
termination_condition_args: {"population_age": 11000, 'no_change_in': 2}

# ===== Genetic algorithm hyperparameters ===== #
pop_size: 100
mig_rate: 0.1
mut_rate: 0.1
rec_rate: 0.3
par_rate: 0.3

# ===== Neural network ===== #
architecture: [64, 100, 10] # Will be overwritten
model: MLP
activation: relu
prune_rate: 0.5
init: uniform
pretrained: None
criterion: CE
mask_except:
  - net.0.bias
  - net.2.bias

# ===== Observer routines ===== #
init_routines: [ir1, ir3, ir4, ir5, ir6, ir7, ir8, ir9, ir12, ir15, ir16, ir17]
evol_routines: [er1, er2, er5, er6, er7, er8, er9, er10, er14, er16]
final_routines: [fr2, fr3, fr6, fr7, fr8, fr10, fr11, fr13, fr15, fr16]
termination_condition: t7

# ===== Parallelization ===== #


